<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Fpp_menu extends MY_Controller
{ 
	/* Module */
 	const  LABELMODULE				= "fpp_menu"; // identify menu
 	const  LABELMASTER				= "Menu FPP";
 	const  LABELFOLDER				= "cash_advance"; // module folder
 	const  LABELPATH				= "fpp_menu"; // controller file (lowercase)
 	const  LABELNAVSEG1				= "cash_advance"; // adjusted 1st sub parent segment
 	const  LABELSUBPARENTSEG1		= "Master"; // 
 	const  LABELNAVSEG2				= ""; // adjusted 2nd sub parent segment
 	const  LABELSUBPARENTSEG2		= ""; // 
	
	/* View */
	public $icon 					= 'fa-database';
	public $tabel_header 			= ["ID","FPP Number","Request Date","Prepared By","Requested By","Total Cost","Status"];

	
	/* Export */
	public $colnames 				= ["ID","FPP Number","Request Date","Prepared By","Requested By","Total Cost","Status"];
	public $colfields 				= ["id","fpp_number","request_date","prepared_by_name","requested_by_name","total_cost","status_name"];



	/* Form Field Asset */
	public function form_field_asset()
	{
		$field = [];

		$getdata = $this->db->query("select * from user where user_id = '".$_SESSION['id']."'")->result(); 
		$karyawan_id = $getdata[0]->id_karyawan;
		$login_name = $this->db->query("select * from employees where id = '".$karyawan_id."'")->result(); 
		$datenow = date("Y-m-d");
		
		$field['txtfppnum'] 	= $this->self_model->return_build_txt('(Generated by System)','fpp_number','fpp_number','','','readonly');
		$field['txtpreparedby'] = $this->self_model->return_build_txt($login_name[0]->full_name,'prepared_by','prepared_by','','','readonly');	
		$field['txtreqdate'] 	= $this->self_model->return_build_txt($datenow,'request_date','request_date','','','readonly');
		$field['txttotalbiaya'] = $this->self_model->return_build_txt('','total_cost','total_cost','','','readonly');
		$field['txtterbilang'] 	= $this->self_model->return_build_txt('','total_cost_terbilang','total_cost_terbilang','','','readonly');
		$field['txtdoc'] 		= $this->self_model->return_build_fileinput('fpp_document','fpp_document');
		$field['rfu_reason']	= $this->self_model->return_build_txtarea('','rfu_reason','rfu_reason');
		$field['reject_reason']	= $this->self_model->return_build_txtarea('','reject_reason','reject_reason');
		$field['txtnorekening']	= $this->self_model->return_build_txt('','no_rekening','no_rekening');

		$field['txtvendorname'] = $this->self_model->return_build_txt('','vendor_name','vendor_name');
		$field['txtinvoicenum'] = $this->self_model->return_build_txt('','invoice_number','invoice_number');
		$field['txtinvoicedate'] = $this->self_model->return_build_txt('','invoice_date','invoice_date');


		$msemp 					= $this->db->query("select * from employees")->result(); 
		$field['txtrequestedby'] 	= $this->self_model->return_build_select2me($msemp,'','','','requested_by','requested_by','','','id','full_name',' ','','','',3,'-');

		$field['txttype'] 		= $this->self_model->return_build_radio('', [['Personal','Personal'],['Company','Company']], 'fpp_type', '', 'inline');
		

		
		return $field;
	}

	//========================== Considering Already Fixed =======================//
 	/* Construct */
	public function __construct() {
        parent::__construct();
		# akses level
		$akses = $this->self_model->user_akses($this->module_name);
		define('_USER_ACCESS_LEVEL_VIEW',$akses["view"]);
		define('_USER_ACCESS_LEVEL_ADD',$akses["add"]);
		define('_USER_ACCESS_LEVEL_UPDATE',$akses["edit"]);
		define('_USER_ACCESS_LEVEL_DELETE',$akses["del"]);
		define('_USER_ACCESS_LEVEL_DETAIL',$akses["detail"]);
		define('_USER_ACCESS_LEVEL_IMPORT',$akses["import"]);
		define('_USER_ACCESS_LEVEL_EKSPORT',$akses["eksport"]);
    }

	/* Module */
 	public $folder_name				= self::LABELFOLDER."/".self::LABELPATH; // module path
 	public $module_name				= self::LABELMODULE;
 	public $model_name				= self::LABELPATH."_model";

	/* Navigation */
 	public $parent_menu				= self::LABELFOLDER;
 	public $subparent_menu			= self::LABELNAVSEG1;
 	public $subparentitem_menu		= self::LABELNAVSEG2;
 	public $sub_menu 				= self::LABELMODULE;

	/* Label */
 	public $label_parent_modul		= self::LABELFOLDER;
 	public $label_subparent_modul	= self::LABELSUBPARENTSEG1;
 	public $label_subparentitem_modul	= self::LABELSUBPARENTSEG2;
 	public $label_modul				= self::LABELMASTER;
 	public $label_list_data			= "Daftar Data ".self::LABELMASTER;
 	public $label_add_data			= "Tambah Data ".self::LABELMASTER;
 	public $label_update_data		= "Edit Data ".self::LABELMASTER;
 	public $label_sukses_disimpan 	= "Data berhasil disimpan";
 	public $label_gagal_disimpan 	= "Data gagal disimpan";
 	public $label_delete_data		= "Hapus Data ".self::LABELMASTER;
 	public $label_sukses_dihapus 	= "Data berhasil dihapus";
 	public $label_gagal_dihapus 	= "Data gagal dihapus";
 	public $label_detail_data		= "Datail Data ".self::LABELMASTER;
 	public $label_import_data		= "Import Data ".self::LABELMASTER;
 	public $label_sukses_diimport 	= "Data berhasil diimport";
 	public $label_gagal_diimport 	= "Import data di baris : ";
 	public $label_export_data		= "Export";
 	public $label_gagal_eksekusi 	= "Eksekusi gagal karena ketiadaan data";

	//============================== Additional Method ==============================//


 	public function genfpprow()
	{ 
		if(_USER_ACCESS_LEVEL_VIEW == "1")
		{ 
			$post = $this->input->post(null, true);

			if(isset($post['count']))
			{  
				$row = trim($post['count']); 
				echo $this->self_model->getNewFppRow($row);
			} else if(isset($post['id'])) { 
				$row = 0;
				$id = trim($post['id']);
				$view = (isset($post['view']) && $post['view'] == TRUE)? TRUE:FALSE;
				echo json_encode($this->self_model->getNewFppRow($row,$id,$view));
			}
		}
		else
		{ 
			$this->load->view('errors/html/error_hacks_401');
		}
	}

	public function delrowDetailFpp(){ 
		$post = $this->input->post(); 
		$id = trim($post['id']); 
		
		if($id != ''){
			$rs = $this->db->delete('fpp_details',"id = '".$id."'");
		}
		
	}



	public function rfu(){
		$post = $this->input->post(null, true);
		$id = $post['id'];
		$reason = $post['reason'];

		if($id != ''){

			$data = [
				'status_id' 	=> 4, //rfu
				'rfu_reason' 	=> $reason,
				'approval_date'	=> date("Y-m-d H:i:s")
			];
			$rs = $this->db->update('fpp', $data, "id = '".$id."'");

			return $rs;
			
		}else return null;

		echo json_encode($rs);

	}


	public function reject(){
		$post = $this->input->post(null, true);
		$id = $post['id'];
		$reason = $post['reason'];

		if($id != ''){

			$data = [
				'status_id' 	=> 3, //reject
				'reject_reason' => $reason,
				'approval_date'	=> date("Y-m-d H:i:s")
			];
			$rs = $this->db->update('fpp', $data, "id = '".$id."'");

			return $rs;
			
		}else return null;

		echo json_encode($rs);

	}


}
