<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Fpu_menu extends MY_Controller
{ 
	/* Module */
 	const  LABELMODULE				= "fpu_menu"; // identify menu
 	const  LABELMASTER				= "Menu FPU";
 	const  LABELFOLDER				= "cash_advance"; // module folder
 	const  LABELPATH				= "fpu_menu"; // controller file (lowercase)
 	const  LABELNAVSEG1				= "cash_advance"; // adjusted 1st sub parent segment
 	const  LABELSUBPARENTSEG1		= "Master"; // 
 	const  LABELNAVSEG2				= ""; // adjusted 2nd sub parent segment
 	const  LABELSUBPARENTSEG2		= ""; // 
	
	/* View */
	public $icon 					= 'fa-database';
	public $tabel_header 			= ["ID","FPU Number","Request Date","Prepared By","Requested By","Status"];

	
	/* Export */
	public $colnames 				= ["ID","FPU Number","Request Date","Prepared By","Requested By","Status"];
	public $colfields 				= ["id","id","id","id","id","id"];

	/* Form Field Asset */
	public function form_field_asset()
	{
		$field = [];

		$getdata = $this->db->query("select * from user where user_id = '".$_SESSION['id']."'")->result(); 
		$karyawan_id = $getdata[0]->id_karyawan;
		$login_name = $this->db->query("select * from employees where id = '".$karyawan_id."'")->result(); 
		$datenow = date("Y-m-d");
		
		$field['txtfpunum'] 	= $this->self_model->return_build_txt('(Generated by System)','fpu_number','fpu_number','','','readonly');
		$field['txtpreparedby'] = $this->self_model->return_build_txt($login_name[0]->full_name,'prepared_by','prepared_by','','','readonly');	
		$field['txtreqdate'] 	= $this->self_model->return_build_txt($datenow,'request_date','request_date','','','readonly');
		$field['txttotalbiaya'] = $this->self_model->return_build_txt('','total_biaya','total_biaya','','','readonly');
		$field['txtterbilang'] 	= $this->self_model->return_build_txt('','total_biaya_terbilang','total_biaya_terbilang','','','readonly');
		$field['txtdoc'] 		= $this->self_model->return_build_fileinput('fpu_document','fpu_document');

		$msemp 					= $this->db->query("select * from employees")->result(); 
		$field['txtrequestedby'] 	= $this->self_model->return_build_select2me($msemp,'','','','requested_by','requested_by','','','id','full_name',' ','','','',3,'-');
		

		
		return $field;
	}

	//========================== Considering Already Fixed =======================//
 	/* Construct */
	public function __construct() {
        parent::__construct();
		# akses level
		$akses = $this->self_model->user_akses($this->module_name);
		define('_USER_ACCESS_LEVEL_VIEW',$akses["view"]);
		define('_USER_ACCESS_LEVEL_ADD',$akses["add"]);
		define('_USER_ACCESS_LEVEL_UPDATE',$akses["edit"]);
		define('_USER_ACCESS_LEVEL_DELETE',$akses["del"]);
		define('_USER_ACCESS_LEVEL_DETAIL',$akses["detail"]);
		define('_USER_ACCESS_LEVEL_IMPORT',$akses["import"]);
		define('_USER_ACCESS_LEVEL_EKSPORT',$akses["eksport"]);
    }

	/* Module */
 	public $folder_name				= self::LABELFOLDER."/".self::LABELPATH; // module path
 	public $module_name				= self::LABELMODULE;
 	public $model_name				= self::LABELPATH."_model";

	/* Navigation */
 	public $parent_menu				= self::LABELFOLDER;
 	public $subparent_menu			= self::LABELNAVSEG1;
 	public $subparentitem_menu		= self::LABELNAVSEG2;
 	public $sub_menu 				= self::LABELMODULE;

	/* Label */
 	public $label_parent_modul		= self::LABELFOLDER;
 	public $label_subparent_modul	= self::LABELSUBPARENTSEG1;
 	public $label_subparentitem_modul	= self::LABELSUBPARENTSEG2;
 	public $label_modul				= self::LABELMASTER;
 	public $label_list_data			= "Daftar Data ".self::LABELMASTER;
 	public $label_add_data			= "Tambah Data ".self::LABELMASTER;
 	public $label_update_data		= "Edit Data ".self::LABELMASTER;
 	public $label_sukses_disimpan 	= "Data berhasil disimpan";
 	public $label_gagal_disimpan 	= "Data gagal disimpan";
 	public $label_delete_data		= "Hapus Data ".self::LABELMASTER;
 	public $label_sukses_dihapus 	= "Data berhasil dihapus";
 	public $label_gagal_dihapus 	= "Data gagal dihapus";
 	public $label_detail_data		= "Datail Data ".self::LABELMASTER;
 	public $label_import_data		= "Import Data ".self::LABELMASTER;
 	public $label_sukses_diimport 	= "Data berhasil diimport";
 	public $label_gagal_diimport 	= "Import data di baris : ";
 	public $label_export_data		= "Export";
 	public $label_gagal_eksekusi 	= "Eksekusi gagal karena ketiadaan data";

	//============================== Additional Method ==============================//


 	public function genfpurow()
	{ 
		if(_USER_ACCESS_LEVEL_VIEW == "1")
		{ 
			$post = $this->input->post(null, true);

			if(isset($post['count']))
			{  
				$row = trim($post['count']); 
				echo $this->self_model->getNewFpuRow($row);
			} else if(isset($post['id'])) { 
				$row = 0;
				$id = trim($post['id']);
				$view = (isset($post['view']) && $post['view'] == TRUE)? TRUE:FALSE;
				echo json_encode($this->self_model->getNewFpuRow($row,$id,$view));
			}
		}
		else
		{ 
			$this->load->view('errors/html/error_hacks_401');
		}
	}

	public function delrowDetailFpu(){ 
		$post = $this->input->post(); 
		$id = trim($post['id']); 
		
		if($id != ''){
			$rs = $this->db->delete('fpu',"id = '".$id."'");
		}
		
	}


}
