<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Settlement_menu extends MY_Controller
{ 
	/* Module */
 	const  LABELMODULE				= "settlement_menu"; // identify menu
 	const  LABELMASTER				= "Menu Settlement";
 	const  LABELFOLDER				= "cash_advance"; // module folder
 	const  LABELPATH				= "settlement_menu"; // controller file (lowercase)
 	const  LABELNAVSEG1				= "cash_advance"; // adjusted 1st sub parent segment
 	const  LABELSUBPARENTSEG1		= "Master"; // 
 	const  LABELNAVSEG2				= ""; // adjusted 2nd sub parent segment
 	const  LABELSUBPARENTSEG2		= ""; // 
	
	/* View */
	public $icon 					= 'fa-database';
	public $tabel_header 			= ["ID","Settlement Number","FPU/FPP Number","Request Date","Prepared By","Requested By","Settlement Amount","Status"];

	
	/* Export */
	public $colnames 				= ["ID","Settlement Number","FPU/FPP Number","Request Date","Prepared By","Requested By","Settlement Amount","Status"];
	public $colfields 				= ["id","settlement_number","ca_number","settlement_date","prepared_by_name","requested_by_name","settlement_amount","status_name"];



	/* Form Field Asset */
	public function form_field_asset()
	{
		$karyawan_id = $_SESSION['worker'];
		$whr='';
		if($_SESSION['role'] != 1){ //bukan super user
			$whr=' AND (id = "'.$karyawan_id.'" OR id = (SELECT direct_id FROM employees WHERE id = "'.$karyawan_id.'" ))';
		}


		$field = [];

		$login_name = $this->db->query("select * from employees where id = '".$karyawan_id."'")->result(); 
		$datenow = date("Y-m-d");
		
		$field['txtsettlementnum'] 	= $this->self_model->return_build_txt('(Generated by System)','settlement_number','settlement_number','','','readonly');
		$field['txtpreparedby'] = $this->self_model->return_build_txt($_SESSION['name'],'prepared_by','prepared_by','','','readonly');	
		$field['txtreqdate'] 	= $this->self_model->return_build_txt($datenow,'request_date','request_date','','','readonly');
		$field['txttotalbiaya'] = $this->self_model->return_build_txt('','total_cost_sett','total_cost_sett','','','readonly');
		$field['txtterbilang'] 	= $this->self_model->return_build_txt('','total_cost_terbilang_sett','total_cost_terbilang_sett','','','readonly');
		$field['txtdoc'] 		= $this->self_model->return_build_fileinput('settlement_document','settlement_document');
		$field['rfu_reason']	= $this->self_model->return_build_txtarea('','rfu_reason','rfu_reason');
		$field['reject_reason']	= $this->self_model->return_build_txtarea('','reject_reason','reject_reason');
		$field['txtcacost'] 	= $this->self_model->return_build_txt('','ca_cost','ca_cost','','','readonly');
		$field['txtsettamount'] = $this->self_model->return_build_txt('','settlement_amount','settlement_amount','','','readonly');

		$field['txtdoc_buktitransfer']	= $this->self_model->return_build_fileinput('bukti_transfer','bukti_transfer');
		$field['txtnorekening'] 		= $this->self_model->return_build_txt('','no_rekening','no_rekening');
		$field['txtbank'] 				= $this->self_model->return_build_txt('','bank','bank');
		$field['txtnamarekening'] 		= $this->self_model->return_build_txt('','nama_rekening','nama_rekening');

		$msemp 						= $this->db->query("select * from employees where status_id = 1 ".$whr." order by full_name asc")->result(); 
		$field['txtrequestedby'] 	= $this->self_model->return_build_select2me($msemp,'','','','requested_by','requested_by','','','id','full_name',' ','','','',3,'-');

		$msca 	= $this->db->query("select * from cash_advance where status_id in ('2','5') and id not in (select cash_advance_id from settlement where status_id = 2)")->result(); 
		$field['selcanumber'] 		= $this->self_model->return_build_select2me($msca,'','','','ca_number','ca_number','','','id','ca_number',' ','','','',3,'-');
		

		
		return $field;
	}

	//========================== Considering Already Fixed =======================//
 	/* Construct */
	public function __construct() {
        parent::__construct();
		# akses level
		$akses = $this->self_model->user_akses($this->module_name);
		define('_USER_ACCESS_LEVEL_VIEW',$akses["view"]);
		define('_USER_ACCESS_LEVEL_ADD',$akses["add"]);
		define('_USER_ACCESS_LEVEL_UPDATE',$akses["edit"]);
		define('_USER_ACCESS_LEVEL_DELETE',$akses["del"]);
		define('_USER_ACCESS_LEVEL_DETAIL',$akses["detail"]);
		define('_USER_ACCESS_LEVEL_IMPORT',$akses["import"]);
		define('_USER_ACCESS_LEVEL_EKSPORT',$akses["eksport"]);
    }

	/* Module */
 	public $folder_name				= self::LABELFOLDER."/".self::LABELPATH; // module path
 	public $module_name				= self::LABELMODULE;
 	public $model_name				= self::LABELPATH."_model";

	/* Navigation */
 	public $parent_menu				= self::LABELFOLDER;
 	public $subparent_menu			= self::LABELNAVSEG1;
 	public $subparentitem_menu		= self::LABELNAVSEG2;
 	public $sub_menu 				= self::LABELMODULE;

	/* Label */
 	public $label_parent_modul		= self::LABELFOLDER;
 	public $label_subparent_modul	= self::LABELSUBPARENTSEG1;
 	public $label_subparentitem_modul	= self::LABELSUBPARENTSEG2;
 	public $label_modul				= self::LABELMASTER;
 	public $label_list_data			= "Daftar Data ".self::LABELMASTER;
 	public $label_add_data			= "Tambah Data ".self::LABELMASTER;
 	public $label_update_data		= "Edit Data ".self::LABELMASTER;
 	public $label_sukses_disimpan 	= "Data berhasil disimpan";
 	public $label_gagal_disimpan 	= "Data gagal disimpan";
 	public $label_delete_data		= "Hapus Data ".self::LABELMASTER;
 	public $label_sukses_dihapus 	= "Data berhasil dihapus";
 	public $label_gagal_dihapus 	= "Data gagal dihapus";
 	public $label_detail_data		= "Datail Data ".self::LABELMASTER;
 	public $label_import_data		= "Import Data ".self::LABELMASTER;
 	public $label_sukses_diimport 	= "Data berhasil diimport";
 	public $label_gagal_diimport 	= "Import data di baris : ";
 	public $label_export_data		= "Export";
 	public $label_gagal_eksekusi 	= "Eksekusi gagal karena ketiadaan data";

	//============================== Additional Method ==============================//


 	public function gensettrow()
	{ 
		if(_USER_ACCESS_LEVEL_VIEW == "1")
		{ 
			$post = $this->input->post(null, true);

			if(isset($post['count']))
			{  
				$row = trim($post['count']); 
				echo $this->self_model->getNewSettRow($row);
			} else if(isset($post['id'])) { 
				$row = 0;
				$id = trim($post['id']);
				$view = (isset($post['view']) && $post['view'] == TRUE)? TRUE:FALSE;
				echo json_encode($this->self_model->getNewSettRow($row,$id,$view));
			}
		}
		else
		{ 
			$this->load->view('errors/html/error_hacks_401');
		}
	}

	public function delrowDetailSett(){ 
		$post = $this->input->post(); 
		$id = trim($post['id']); 
		
		if($id != ''){
			$rs = $this->db->delete('settlement_details',"id = '".$id."'");
		}
		
	}



	public function rfu(){ 
		
		$karyawan_id = $_SESSION['worker'];


		$post = $this->input->post(null, true);
		$id = $post['id'];
		$reason = $post['reason'];
		$approval_level = $post['approval_level'];

		if($id != ''){

			$data = [
				'status_id' 	=> 4, //rfu
				'rfu_reason' 	=> $reason,
				'approval_date'	=> date("Y-m-d H:i:s")
			];
			$rs = $this->db->update('settlement', $data, "id = '".$id."'");
			if($rs){ 
				$CurrApproval = $this->getCurrApproval($id, $approval_level);
				if(!empty($CurrApproval)){
					$CurrApprovalId		= $CurrApproval[0]->id;
					$CurrApprovalPathId = $CurrApproval[0]->approval_path_id;
					
					$updApproval = [
						'status' 		=> "Request for Update",
						'approval_by' 	=> $karyawan_id,
						'approval_date'	=> date("Y-m-d H:i:s")
					];
					$this->db->update("approval_path_detail", $updApproval, "id = '".$CurrApprovalId."'");

				}
			}

			return $rs;
			
		}else return null;

		echo json_encode($rs);

	}


	public function reject(){
	 
		$karyawan_id = $_SESSION['worker'];


		$post = $this->input->post(null, true);
		$id = $post['id'];
		$reason = $post['reason'];
		$approval_level = $post['approval_level'];

		if($id != ''){

			$data = [
				'status_id' 	=> 3, //reject
				'reject_reason' => $reason,
				'approval_date'	=> date("Y-m-d H:i:s")
			];
			$rs = $this->db->update('settlement', $data, "id = '".$id."'");
			if($rs){
				$CurrApproval = $this->getCurrApproval($id, $approval_level);
				if(!empty($CurrApproval)){
					$CurrApprovalId		= $CurrApproval[0]->id;
					$dataapproval = [
						'status' 		=> "Rejected",
						'approval_by' 	=> $karyawan_id,
						'approval_date'	=> date("Y-m-d H:i:s")
					];
					$this->db->update("approval_path_detail", $dataapproval, "id = '".$CurrApprovalId."'");
				}
			}

			return $rs;
			
		}else return null;

		echo json_encode($rs);

	}


	public function getDataCashadvance(){
		$post = $this->input->post(null, true);
		$id = $post['id'];

		$rs =  $this->self_model->getDataCashadvance($id);
		

		echo json_encode($rs);
	}


	public function getDataEmp(){
		$post = $this->input->post(null, true);
		$employee_id = $post['employee_id'];

		$rs = $this->db->query("select * from employees where id = '".$employee_id."' ")->result(); 
		

		echo json_encode($rs);
	}


	public function getApprovalLog() {
	    $post = $this->input->post(null, true);
	    $id = $post['id'];
	    $approval_matrix_type_id = 3; //settlement

	   

	    $query = "
	        select a.*, c.approval_level, d.role_name, e.id as 'id_detail',
				(case when e.id != '' and (e.status = '' or e.status is null) and a.current_approval_level = c.approval_level then 'Waiting Approval'
				when e.id != '' and e.status != '' then e.status
				else ''
				end) as status_name,
				IF(e.id != '' and e.status != '', (SELECT full_name FROM employees WHERE id = e.approval_by), d.role_name) AS approver_name,
				e.approval_date
			from approval_path a 
			left join approval_matrix b on b.id = a.approval_matrix_id
			left join approval_matrix_detail c on c.approval_matrix_id = b.id
			left join approval_matrix_role d on d.id = c.role_id
			left join approval_path_detail e on e.approval_path_id = a.id and e.approval_level = c.approval_level
				where a.approval_matrix_type_id = ".$approval_matrix_type_id." and a.trx_id = '".$id."'
			order by c.approval_level asc
	    ";

	    $rs = $this->db->query($query)->result();

	    $dt = '';
	    if (!empty($rs)) {
	        foreach ($rs as $row) {
	        	$approval_date = $row->approval_date;
	        	if($row->approval_date == '0000-00-00 00:00:00' || $row->approval_date == ''){
	        		$approval_date = '';
	        	}
	        	
	            $dt .= '<tr>';
	            $dt .= '<td>'.$row->approval_level.'</td>';
	            $dt .= '<td>'.$row->approver_name.'</td>';
	            $dt .= '<td>'.$row->status_name.'</td>';
	            $dt .= '<td>'.$approval_date.'</td>';
	            $dt .= '</tr>';
	        }
	    } else {
	        $dt .= '<tr><td colspan="4" class="text-center text-muted">No data</td></tr>';
	    }

	    echo json_encode(['html' => $dt]);
	}


	public function getCurrApproval($trx_id, $approval_level){

		$approval_matrix_type_id = 3; //settlement
		$rs =  $this->db->query("select b.* from approval_path a left join approval_path_detail b on b.approval_path_id = a.id and approval_level = ".$approval_level." where a.approval_matrix_type_id = ".$approval_matrix_type_id." and a.trx_id = ".$trx_id."")->result();
		

		return $rs;
	}

}
